### ISSUE TITLE
Synthetic data generator

### ISSUE THREAD

**Issue by nzarif** [harvard-acc/DeepRecSys#1]
Hi,

Thanks a lot for the useful infrastructure and high-quality code. If we want to generate synthetic data using the data generators, we need to have a workload file or the "sd_cumm" and "sd_prob" files can be used as the input of "trace_profile.py"? Or "sd_cumm" and "sd_prob" are the results of a trace profiling that you have already done?

**Comment by alugupta** [comment]
Hi @nzarif, 

Thanks for the comment and interest in DeepRecSys! The trace_profile.py is mean to generate the sd_cumm and sd_prob files based on a provided input trace while the trace_generator will generate a synthetic trace based on the embedding lookup distribution descrbied in sd_cumm and sd_prob. Alternatively, you may use open-source datasets such as MovieLens or Criteo Kaggle
