### ISSUE TITLE
Requeriments

### ISSUE THREAD

**Issue by ivanfv** [harvard-acc/DeepRecSys#2]
Hello,

I am trying to use DeepRecSys on a machine that has installed Ubuntu 18.04, but I have problems when trying to install the dependencies (pip3 install -r build/pip_requirements.txt) since some specific package versions are not found. I also have problems to install caffe2.

Would DeepRecSys work on a Ubuntu 18.04 machine or should I try on another version?

Thanks,
Ivan

**Comment by alugupta** [comment]
Hi,

Thanks for reaching out. Could you clarify what sort of problems you are running into when installing the dependencies and caffe2?

Udit

**Comment by ivanfv** [comment]
Hi,

I am using Ubuntu 18.04, and when I execute pip install -r build/pip_requirements.txt, I obtain several errors related to the versions defined in the requirements file, for example:

`Could not find a version that satisfies the requirement kiwisolver==1.2.0 (from -r build/pip_requirements.txt (line 8)) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 1.0.0, 1.0.1, 1.1.0) No matching distribution found for kiwisolver==1.2.0 (from -r build/pip_requirements.txt (line 8))`

And I don't know if it is fine to install another version of those packages.

Thanks,
Ivan

**Comment by samhsia** [comment]
It seems like kiwisolver does have a working 1.2.0 version (see [here](https://pypi.org/project/kiwisolver/)). 
However, it should be fine to use an older version of kiwisolver for the purposes of this repository.

Please let us know if this doesn't work!
