### ISSUE TITLE
supporting the inference on a real GPU

### ISSUE THREAD

**Issue by Jeongseob** [harvard-acc/DeepRecSys#3]
Hi,

As far as I know, it does not support the inference on a real GPU. The code used in this open source does not take the actual GPU inference. Instead, it mimics the GPU inference by waiting a fixed time based on an analytic model. Is there a reason not to use an actual GPU? Since DLRM has supported the GPU inference, I am wondering why this version does exclude the GPU side code. 

Thanks,
Jeongseob

**Comment by samhsia** [comment]
In terms of the end-to-end infrastructure, the reason behind this is a combination of engineering and research. Python’s GIL prevents multiple processes from accessing the GPU. Given the current setup, either all processes will be GPU-enabled or none will be. One way to get around this is selectively setting the GPU flag for only 1 process.

From a research perspective, the hope is to allow other accelerator models to be evaluated at-scale. To model how GPUs perform on inference workloads for the different models, you can try taking a look at the `operator_breakdown` and `speedup` sample experiments within the `experiments` directory. More specifically, the flag to use GPU during inference is `--use_accel`.

You are also more than welcome to implement a real-time GPU backend for the end-to-end infrastructure :-) 

Hope this helps!
