### ISSUE TITLE
Running DLRM with synthetic inputs

### ISSUE THREAD

**Issue by rajesh-iiith** [harvard-acc/DeepRecSys#5]
After I generated synthetic trace using data_generator/trace_generator.py, I am trying to run the dlrm_s_caffe2 in synthetic mode (using the command below). It keeps compiling about "'Namespace' object has no attribute 'data_size'". If I try to pass some value by --data_size, it doesn't recognize this argument.

python dlrm_s_caffe2.py --inference_only --caffe2_net_type async_dag --config_file "configs/dlrm_rm2.json" --engine "prof_dag" --nepochs 100 --data_generation "synthetic" --round_targets 10 --num_batches 512 --mini_batch_size 16 --max_mini_batch_size 16 --data_trace_file "../data_generator/syn_traces/tbl1"

Am I doing something wrong? Can you provide a sample command line to run dlrm with synthetic inputs?

**Comment by alugupta** [comment]
Hi @rajesh-iiith , I am curious if you have been able to run some of the provided experiments, like the operator breakdown sweep: https://github.com/harvard-acc/DeepRecSys/tree/master/experiments/operator_breakdown 

This will help know whether it is a tool/versioning issue or if there is something else going on. 

You can also print out the commands being issued in that sweep ([link](https://github.com/harvard-acc/DeepRecSys/blob/master/experiments/operator_breakdown/sweep_p.py#L64)) as examples.
