### ISSUE TITLE
operator breakdown on larger models

### ISSUE THREAD

**Issue by EtoDemerzel0427** [harvard-acc/DeepRecSys#7]
Dear authors,

After the discussion with you last week, I had a chance to do some experiments on larger models. However, the results do not align well with my expectations.

The configs are as follows:
```json
{
    "arch_mlp_bot": "13-256-32",
    "arch_mlp_top": "256-128-1",
    "arch_embedding_size": "39043-17289-7420-20263-7120-403346-976-147-39979772-25641295-39664985-585935", 
    "arch_sparse_feature_size": 32,
    "num_indices_per_lookup_fixed": true,
    "num_indices_per_lookup": 35,
    "arch_interaction_op": "cat",
    "model_type": "dlrm",
    "model_name": "rm1"
}

{
    "arch_mlp_bot": "13-512-256-64",
    "arch_mlp_top": "512-512-256-1",
    "arch_embedding_size": "39884407-39043-17289-7420-20263-315-7120-1543-263-38532952-2953546-403346-108-2208-11938-155-408-976-147-39979772-25641295-39664985-585935-12972-108-236",
    "arch_sparse_feature_size": 64,
    "num_indices_per_lookup_fixed": true,
    "num_indices_per_lookup": 35,
    "arch_interaction_op": "cat",
    "model_type": "dlrm",
    "model_name": "rm1"
}

{
    "arch_mlp_bot": "2560-1024-256-32",
    "arch_mlp_top": "512-256-1",
    "arch_embedding_size": "39884407-39043-17289-7420-20263-310-7120-1543-263-155-400-976-147-39979772-25641295-39664985-58 5935-12972-108-236",
    "arch_sparse_feature_size": 32,
    "num_indices_per_lookup_fixed": true,
    "num_indices_per_lookup": 20,
    "arch_interaction_op": "cat",
    "model_type": "dlrm",
    "model_name": "rm3"
}
```
You can see there are 13.6GB, 48.1GB, 18.6GB embedding tables on RMC-1, RMC-2, and RMC-3 respectively. I think RMC-2 would spend more time on SLS as its embedding tables are really large compared to the FC layers. But the results are different.

The breakdown figure is:
![image](https://user-images.githubusercontent.com/32998901/116129655-f0643300-a6fc-11eb-9543-11b40577982e.png)

For your reference, it is a piece of log when batch size is 256 on RMC-2:
```shell
Time per operator type:
        18.6277 ms.    70.1539%. FC
        6.78981 ms.    25.5711%. SparseLengthsSum
        0.76081 ms.    2.86529%. Concat
       0.369324 ms.    1.39091%. Relu
       0.004991 ms.  0.0187966%. Sigmoid
        26.5526 ms in Total
FLOP per operator type:
       0.733889 GFLOP.    98.0089%. FC
      0.0149094 GFLOP.    1.99112%. SparseLengthsSum
              0 GFLOP.          0%. Concat
              0 GFLOP.          0%. Relu
       0.748798 GFLOP in Total
Feature Memory Read per operator type:
        60.5962 MB.    81.7255%. SparseLengthsSum
        9.61767 MB.    12.9712%. FC
        2.16269 MB.    2.91679%. Relu
        1.76948 MB.    2.38647%. Concat
        74.1461 MB in Total
Feature Memory Written per operator type:
        2.16371 MB.    35.4947%. FC
        2.16269 MB.    35.4779%. Relu
        1.76947 MB.    29.0274%. Concat
              0 MB.          0%. SparseLengthsSum
        6.09587 MB in Total
Parameter Memory per operator type:
        48068.8 MB.    99.9881%. SparseLengthsSum
        5.73773 MB.  0.0119351%. FC
              0 MB.          0%. Concat
              0 MB.          0%. Relu
        48074.5 MB in Total
```
I know compared to FC, SLS's compute intensity is really low, so when it still takes 25% of the total time, we should regard it as a considerable amount. But this figure is very different from that in your paper, so I am wondering what was wrong with this.  Is it that I configured RMC-2 wrongly?

My CPU info is as below:
```shell
architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
Stepping:              4
CPU MHz:               899.926
CPU max MHz:           3000.0000
CPU min MHz:           800.0000
BogoMIPS:              4400.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              14080K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d
```

Thanks!

**Comment by samhsia** [comment]
Hi @EtoDemerzel0427 , thanks for your question and checking out the experiments!

The reason why the results do not align well with your expectations is that the model configurations in which you've used are not in line with the ones we've included in the repository (i.e., the ones that we've used for our paper). More specifically, RM2 has more indices per lookup operation and its MLP sizes are smaller.

**Comment by EtoDemerzel0427** [comment]
> Hi @EtoDemerzel0427 , thanks for your question and checking out the experiments!
> 
> The reason why the results do not align well with your expectations is that the model configurations in which you've used are not in line with the ones we've included in the repository (i.e., the ones that we've used for our paper). More specifically, RM2 has more indices per lookup operation and its MLP sizes are smaller.

Thanks for your reply. To my understanding, RMC-1/2/3 are categories of recommendation models instead of specific model configs. So are there any rules for building and distinguishing them? Especially when we want to build larger versions of these models, I found it a bit subtle, as I previously thought a "13-512-256-64" bottom MLP and a "512-512-256-1" top MLP are already very small compared with the 48GB embedding table.

BTW, [DLRM](https://github.com/facebookresearch/dlrm) also released DLRM on Kaggle and Terabyte datasets (the embedding table sizes and MLP sizes I used come from it), and one of its main property is that the embedding lookup number on each table is only one. Which kind of RM is it?

Thanks again.

**Comment by alugupta** [comment]
Hi @EtoDemerzel0427 , You are right that RMC-1/2/3 are categories of models as opposed to specific model configs. In terms of scaling, we would suggest scaling the models with respect to one another. The exact scaling factors will depend on industry use cases.

In terms of the DLRM implementation on Kaggle and Terabyte data sets they use one-hot encoded as you point out. Because of the one-hot encoded lookups the models follow the Wide-and-Deep (WnD) model in the DeepRecSys repository.

**Comment by EtoDemerzel0427** [comment]
> Hi @EtoDemerzel0427 , You are right that RMC-1/2/3 are categories of models as opposed to specific model configs. In terms of scaling, we would suggest scaling the models with respect to one another. The exact scaling factors will depend on industry use cases.
> 
> In terms of the DLRM implementation on Kaggle and Terabyte data sets they use one-hot encoded as you point out. Because of the one-hot encoded lookups the models follow the Wide-and-Deep (WnD) model in the DeepRecSys repository.

Thanks for the reply. I am a bit surprised to hear that the open-sourced DLRM model (which is also benchmarked in MLCommons) is actually following another pattern other than the RMCs at Facebook. So, it means if we want to investigate the performance problems you've mentioned in https://arxiv.org/pdf/1906.03109.pdf, we should not use the Kaggle/Terabyte as our experimental target?

**Comment by EtoDemerzel0427** [comment]
BTW, I also have another (orthogonal) question. As in the DeepRecSys paper, GPUs start to outperform CPUs on all RMC-1/2/3 when batch sizes are relatively small. Nvidia also demonstrated their power in this post: https://developer.nvidia.com/blog/optimizing-dlrm-on-nvidia-gpus/.  It sounds like using GPUs is a good idea, but in https://arxiv.org/pdf/1906.03109.pdf, seems that Facebook is using only CPUs to do recommendation inferences. What is the reason behind this?
