### ISSUE TITLE
`inferenceEngineReadyQueue.put(True)` in a while loop?

### ISSUE THREAD

**Issue by SungMinCho** [harvard-acc/DeepRecSys#9]
https://github.com/harvard-acc/DeepRecSys/blob/f07ef3fdd125779a45859e33b1b73d2186d2d433/inferenceEngine.py#L190-L191

Should this be in a while loop?

From what I understand, each inference engine should signal the ReadyQueue **only once**, just as in `accelInferenceEngine` for example:

https://github.com/harvard-acc/DeepRecSys/blob/f07ef3fdd125779a45859e33b1b73d2186d2d433/accelInferenceEngine.py#L33-L34

Also, the queue is consumed for exactly `args.inference_engines` number of times, and is not consumed anymore afterwards

https://github.com/harvard-acc/DeepRecSys/blob/f07ef3fdd125779a45859e33b1b73d2186d2d433/loadGenerator.py#L76-L78

It seems like the statement in the while loop will keep piling elements in the ReadyQueue for each request that it handles, and if it reaches the maximum queue size (32767?) it might cause some sort of a deadlock, it seems.

Please confirm whether I understood correctly.

Thanks.

**Comment by alugupta** [comment]
Dear SungMinCho,

You are correct that the ```   inferenceEngineReadyQueue.put(True)``` should be run only once and moved to the above (outside) the start of the ```while``` loop. If you could make the pull request I can help approve the change. 

Thank you for catching this error and suggesting the fix!
